//
// Created by OWNER on 7/19/2023.
//

#ifndef ARGOS3_DEEPRACER_REAL_DEEPRACER_DIFFERENTIAL_STEERING_DEVICE_H
#define ARGOS3_DEEPRACER_REAL_DEEPRACER_DIFFERENTIAL_STEERING_DEVICE_H



class real_deepracer_differential_steering_device {

};



#endif //ARGOS3_DEEPRACER_REAL_DEEPRACER_DIFFERENTIAL_STEERING_DEVICE_H
