//
// Created by OWNER on 7/12/2023.
//

#ifndef ARGOS3_DEEPRACER_CI_DEEPRACER_ACCELEROMETER_SENSOR_H
#define ARGOS3_DEEPRACER_CI_DEEPRACER_ACCELEROMETER_SENSOR_H



class ci_deepracer_accelerometer_sensor {

};



#endif //ARGOS3_DEEPRACER_CI_DEEPRACER_ACCELEROMETER_SENSOR_H
