//
// Created by OWNER on 7/11/2023.
//

#ifndef ARGOS3_DEEPRACER_CI_DEEPRACER_CAMERA_SENSOR_H
#define ARGOS3_DEEPRACER_CI_DEEPRACER_CAMERA_SENSOR_H



class ci_deepracer_camera_sensor {

};



#endif //ARGOS3_DEEPRACER_CI_DEEPRACER_CAMERA_SENSOR_H
