//
// Created by OWNER on 8/6/2023.
//

#ifndef ARGOS3_DEEPRACER_DYNAMICS2D_ACKERMANSTEERING_CONTROL_H
#define ARGOS3_DEEPRACER_DYNAMICS2D_ACKERMANSTEERING_CONTROL_H



class dynamics2d_ackermansteering_control {

};



#endif //ARGOS3_DEEPRACER_DYNAMICS2D_ACKERMANSTEERING_CONTROL_H
